[package]
name = "seabrew"
version = "0.0.1"
authors = ["Ryan Maynard <hi@ryanmaynard.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
